name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Copy jar to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: build/libs/shoppingmall-0.0.1-SNAPSHOT.jar
          target: ~/shoppingmall/

      - name: SSH into EC2 and run app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            mkdir -p ~/app
            pkill -f 'java -jar' || true
            sleep 2
            mv ~/shoppingmall/shoppingmall-0.0.1-SNAPSHOT.jar ~/app/
            cd ~/app
            nohup java -jar shoppingmall-0.0.1-SNAPSHOT.jar > app.log 2>&1 < /dev/null &
            sleep 3
            echo " App started successfully"
