- name: SSH into EC2 and run app
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_KEY }}
    script: |
      mkdir -p ~/app
      sudo pkill -f 'java -jar' || true
      mv ~/shoppingmall/shoppingmall-0.0.1-SNAPSHOT.jar ~/app/
      cd ~/app
      setsid java -jar shoppingmall-0.0.1-SNAPSHOT.jar > app.log 2>&1 < /dev/null &
